theme: jekyll-theme-primer
title: Introduction
description: Alzheimer's Project Introduction
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
